README.md

feat(readme): make description generic

---

crunch/__version__.py
crunch/api/domain/metric.py
crunch/scoring/reducers.py

- api: rename `CUMPROD_PLUS_MINUS_1` to `PRODUCT_PLUS_MINUS_1`

3.0.0 beta 5

---

crunch/__version__.py
crunch/api/client.py
crunch/api/domain/__init__.py
crunch/api/domain/competition.py
crunch/api/domain/data_release.py
crunch/api/domain/quickstarter.py
crunch/command/quickstarter.py
crunch/utils.py
tests/api/test_client.py

- api: add competition format enum
- quickstarter: add competition format
- api: allow some column names field to be null
- download: allow pickle files

3.0.0 beta 7

---

crunch/__version__.py
crunch/api/__init__.py
crunch/api/errors.py
crunch/checker/checker.py
crunch/checker/functions.py
crunch/command/test.py
crunch/ensure.py
crunch/inline.py
crunch/store.py
crunch/tester.py
crunch/utils.py
tests/checker/test_functions.py

- check: allow any function to run at any scope
- runner: support dag competition
- store: disable .env load verbose

3.0.0 beta 8

---

crunch/__version__.py
crunch/api/domain/data_release.py
crunch/api/domain/score.py
crunch/cli.py
crunch/orthogonalization/__init__.py
crunch/runner/cloud.py
crunch/runner/cloud_executor.py
crunch/scoring/score.py

- runner/cloud: download y raw
- scoring: losing types
- data-release: y raw file

feat(runner/cloud): download y raw

---

.github/workflows/pytest.yml
crunch/__version__.py

Doing Python is really frustrating...
- pytest: build and install the wheel before running the tests to make sure all files will be included
- scoring: add missing `__init__.py` because `_format/` directory was not included in built package

fix(scoring): add missing `__init__.py`

---

crunch/__version__.py
crunch/command/setup.py

- setup: remove debug code always triggering a quickstarter setup

fix(setup): remove debug code

---

crunch/__version__.py
crunch/api/domain/round.py
crunch/orthogonalization/__init__.py
crunch/orthogonalization/orthogonalize.py

- orthogonalization: add timeout

feat(orthogonalization): add read timeout

---

crunch/__version__.py
crunch/benchmark/__init__.py
crunch/benchmark/orthogonalization.py
crunch/cli.py
crunch/store.py
requirements/default.txt
requirements/runner.txt

- benchmark: orthogonalization
- store: only update `debug` if not true
- requirements: add astor

feat(benchmark): orthogonalization

---

crunch/__version__.py
crunch/inline.py
crunch/orthogonalization/__init__.py

- inline: expose `alpha_score` parameters

feat(inline): expose `alpha_score` parameters

---

crunch/__version__.py
crunch/api/client.py
requirements/default.txt
requirements/runner.txt

- api/client: show progress bar for file upload (when debug is enabled)

feat(api): show upload progress bar

---

crunch/__version__.py
crunch/api/client.py
crunch/api/domain/submission.py
crunch/command/push.py
requirements/default.txt
requirements/runner.txt

- push: log current server progress in creating submission

feat(push): handle server reporting

---

crunch/__version__.py
crunch/cli.py
crunch/utils.py

- utils: ignore input type, trust file extension

fix(inline): cannot load dag data

---

crunch/__version__.py
crunch/runner/local.py

This change should have been part of 7b1c4b5e12296c91a0b510f8e7a614ae1d750b2f.

fix(runner/local): forgot to remove parameter for 3.9.2

---

crunch/__version__.py
crunch/api/client.py
crunch/api/domain/__init__.py
crunch/api/domain/phase.py
crunch/api/domain/submission.py
crunch/api/domain/submission_file.py
crunch/api/errors.py
crunch/cli.py
crunch/command/push.py
crunch/utils.py

- api/errors: add `RestrictedPhaseActionException`
- cli/push: print file with hardcoded string
- cli/update-token: prompt if new token not specified
- error: detect competition name from project

feat(submission): hardcoded string error message

---

crunch/__version__.py
crunch/api/domain/runner.py
crunch/cli.py
crunch/command/test.py
crunch/inline.py
crunch/runner/cloud.py
crunch/runner/local.py
crunch/runner/runner.py
crunch/tester.py

- runner: run infer twice if derterminism check is enabled
- After: https://github.com/crunchdao/crunch-cli/pull/71

feat(runner): add determinism check

---

.github/workflows/pytest.yml
crunch/__version__.py
crunch/api/client.py
crunch/api/domain/competition.py
crunch/api/domain/data_release.py
crunch/api/domain/prediction.py
crunch/api/domain/project.py
crunch/api/domain/run.py
crunch/api/domain/score.py
crunch/api/domain/submission.py
crunch/api/resource.py
crunch/cli.py
crunch/command/init.py
crunch/command/setup.py
crunch/runner/columns.py
crunch/scoring/_format/dag.py
crunch/scoring/score.py
crunch/utils.py
tests/api/test_client.py
tests/runner/test_columns.py

As the unit test contact the API, the platform will have to be merged first.
- api: change all project dependant endpoint to include the project name
- api/data-release: `targets` are stored in a list

feat: multiple project support

---

crunch/__version__.py
crunch/api/domain/__init__.py
crunch/api/domain/data_release.py
crunch/api/errors.py
crunch/cli.py
crunch/command/download.py
crunch/command/push.py
crunch/container.py
crunch/inline.py
crunch/runner/__init__.py
crunch/runner/cloud.py
crunch/runner/cloud_executor.py
crunch/runner/local.py
crunch/runner/runner.py
tests/test_container.py

- api/data-release: add feature list
- api/errors: add `CurrentPhaseNotFoundException`
- runner: provide `feature_column_names` parameter
- command/push: project url not included in url
- runner/cloud: target column names not properly sent

feat(data-release): feature list

---

crunch/__version__.py
crunch/scoring/_format/timeseries.py
crunch/scoring/score.py

- timeseries: only merge for specified targets

feat(timeseries): only merge with specified metrics

---

crunch/runner/local.py

- runner/local/dag: code is using a removed property

fix(runner/local): use of removed property

---

crunch/api/domain/data_release.py
crunch/api/domain/metric.py
crunch/scoring/reducers.py
crunch/scoring/score.py

- api/metrics: add `ReducerFunction.NONE`
- scoring: handle `NONE` reducer

feat(api/metrics): `ReducerFunction.NONE`

---

crunch/scoring/_format/dag.py
crunch/scoring/score.py

After testing the dag merge with the full 47,000 datasets, optimizations were needed to make it viable in production.
- dag/merge: optimize `get_labels`, reduced from 5min to 1min

perf(dag/merge): optimize `get_labels`

---

crunch/checker/checker.py

- checker: add suffix in exception message
```
Before: Values are not between 0.0 and 1.0
After: Values are not between 0.0 and 1.0 on column=`prediction_w`
```

fix(checker): add suffix in exception message

---

crunch/api/domain/__init__.py
crunch/api/domain/submission.py
crunch/api/errors.py
crunch/cli.py
crunch/command/__init__.py
crunch/command/push.py
crunch/command/push_prediction.py

- command/push-prediction: add

feat(command/push-prediction): add

---

crunch/runner/local.py
crunch/runner/runner.py
crunch/tester.py

- inline: return prediction after test

fix(inline): return prediction after test

---

crunch/scoring/_format/dag.py

- scoring/dag: raise an exception if bad graph instead of using `assert`s

chore(scoring/dag): raise if bad graph

---

crunch/utils.py
tests/test_utils.py

- utils/cut-url: remove `//` from the url's scheme

feat(utils/cut-url): remove schema

---

crunch/utils.py

Continuation of #96.
If a user model had a lot of files, doing double requests slowed down the runner.

feat(utils/download): use head connection

---

crunch/runner/cloud.py

- runner/cloud: send `--chown-directory {model_directory_path}` to the sandbox

feat(runner/cloud): send `--chown-directory {model_directory_path}` to the sandbox

---

crunch/monkey_patches.py

- monkey-patch/tqdm: set `mininterval` to at least `10` seconds, force if missing or invalid

feat(tqdm): set `mininterval` to `10` seconds

---

crunch/scoring/_format/dag.py

- scoring/dag: reverse bit-shifts (see #103)

fix(scoring/dag): reverse bit-shifts

---

crunch/api/domain/__init__.py
crunch/api/domain/competition.py
crunch/api/domain/enum_.py
crunch/cli.py
crunch/container.py
crunch/ensure.py
crunch/inline.py
crunch/runner/cloud.py
crunch/runner/cloud_executor.py
crunch/runner/local.py
crunch/runner/runner.py
crunch/scoring/score.py
crunch/utils.py
tests/test_container.py

- api/competition: add `Format.STREAM`
- runner: add stream competition format

feat(runner): add stream competition support

---

.vscode/settings.json
crunch/api/domain/data_release.py
crunch/cli.py
crunch/runner/cloud.py
crunch/runner/cloud_executor.py
crunch/runner/local.py
crunch/runner/runner.py
crunch/scoring/_format/stream.py
crunch/scoring/score.py
crunch/utils.py
tests/test_container.py

- runner: support new stream data shape

feat(stream): new data shape

---

crunch/api/domain/check.py
crunch/api/domain/metric.py

- api/check: wrong return type for listing function
- api/metric: wrong return type for listing function

fix(api): list typing

---

crunch/api/domain/metric.py
crunch/command/test.py
crunch/container.py
crunch/inline.py
crunch/meta.py
crunch/runner/cloud.py
crunch/runner/cloud_executor.py
crunch/runner/local.py
crunch/runner/runner.py
crunch/scoring/_format/stream.py
crunch/scoring/score.py
crunch/scoring/scorers.py
crunch/tester.py
tests/test_container.py
tests/test_meta.py

- scoring: meta execution time

feat(scoring): execution time

---

crunch/scoring/score.py

- score: return a `reduced` property

feat(scoring): add `reduced` property

---

crunch/checker/checker.py
crunch/checker/functions.py

Add support for stream competition format's predictions.

feat(check): stream competition

---

crunch/api/domain/data_release.py
crunch/command/download.py
crunch/utils.py

> [!WARNING]  
> Currently systems that depends on the old structured download. (Like the `crunch test`)
- command/download: download all files, not just the regular structure

feat(download)!: download custom files

---

crunch/cli.py
crunch/constants.py
crunch/store.py

- cli: add `--environment [production|staging|development]` option

feat(cli): allow for more environment than staging

---

crunch/cli.py
crunch/command/test.py
crunch/runner/local.py
crunch/unstructured/execute.py
crunch/unstructured/module/runner.py
crunch/utils.py

The limiter can only exit and this is an issue when we are running in a notebook.
The simplest way is to just remove it as it could complicate finding the root cause anyway.

revert: #244
